// PDF Report Generation
// Uses jsPDF + AutoTable for CSRD compliance reports

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Supplier, Violation, SimulationOutput } from '@/types';

const FOOTER_TEXT = [
  'Report generated by Scope3Scout',
  'Data sourced from public records',
  'For compliance use only',
];

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const retrievedDate = new Date().toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Separator line
    doc.setDrawColor(200, 200, 200);
    doc.line(14, pageHeight - 30, pageWidth - 14, pageHeight - 30);

    doc.setFontSize(7);
    doc.setTextColor(130, 130, 130);
    doc.text(FOOTER_TEXT[0], 14, pageHeight - 24);
    doc.text(FOOTER_TEXT[1], 14, pageHeight - 20);
    doc.text(`Retrieved: ${retrievedDate}`, 14, pageHeight - 16);
    doc.text(FOOTER_TEXT[2], 14, pageHeight - 12);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 12, {
      align: 'right',
    });

    // Reset text color
    doc.setTextColor(0, 0, 0);
  }
}

function formatDate(dateStr: string | null): string {
  if (!dateStr) return 'N/A';
  return new Date(dateStr).toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function generateSupplierReport(
  supplier: Supplier,
  violations: Violation[],
  simulation: SimulationOutput | null
): jsPDF {
  const doc = new jsPDF();
  const generatedDate = formatDate(new Date().toISOString());

  // ── Page 1: Header & Supplier Details ──

  doc.setFontSize(20);
  doc.text('Scope3Scout', 14, 22);
  doc.setFontSize(12);
  doc.text('Supplier Risk & Compliance Report', 14, 30);

  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${generatedDate}`, 14, 38);
  doc.text('Classification: For Compliance Use Only', 14, 43);
  doc.setTextColor(0, 0, 0);

  // Supplier info table
  doc.setFontSize(14);
  doc.text('1. Supplier Details', 14, 56);

  autoTable(doc, {
    startY: 60,
    theme: 'grid',
    headStyles: { fillColor: [34, 87, 60] },
    head: [['Field', 'Value']],
    body: [
      ['Supplier Name', supplier.name],
      ['Country', supplier.country || 'N/A'],
      ['Industry', supplier.industry || 'N/A'],
      ['Website', supplier.website || 'N/A'],
      ['Current Status', supplier.status.toUpperCase()],
      ['Risk Score', `${supplier.risk_score}/100`],
      ['Risk Level', supplier.risk_level.toUpperCase()],
      ['Last Scanned', formatDate(supplier.last_scanned_at)],
    ],
    margin: { bottom: 35 },
  });

  // ── Page 2+: Violations with Evidence ──

  if (violations.length > 0) {
    doc.addPage();
    doc.setFontSize(14);
    doc.text('2. Violations & Evidence Record', 14, 22);

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`${violations.length} violation(s) found on record`, 14, 29);
    doc.setTextColor(0, 0, 0);

    let currentY = 36;

    violations.forEach((v, index) => {
      // Check if we need a new page (leave room for content + footer)
      if (currentY > 220) {
        doc.addPage();
        currentY = 22;
      }

      // Violation header
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`VIOLATION #${index + 1}`, 14, currentY);
      currentY += 6;

      // Violation details table
      const violationBody: string[][] = [
        ['Type', v.type.charAt(0).toUpperCase() + v.type.slice(1)],
        ['Severity', v.severity.toUpperCase()],
        ['Description', v.description],
        ['Fine Amount', v.fine_amount_eur > 0 ? `EUR ${v.fine_amount_eur.toLocaleString()}` : 'N/A'],
        ['Date Found', formatDate(v.found_at)],
      ];

      autoTable(doc, {
        startY: currentY,
        theme: 'grid',
        headStyles: { fillColor: [34, 87, 60] },
        head: [['Field', 'Value']],
        body: violationBody,
        columnStyles: {
          0: { cellWidth: 40, fontStyle: 'bold' },
          1: { cellWidth: 'auto' },
        },
        margin: { bottom: 35 },
      });

      // Get the Y position after the table
      currentY = ((doc as unknown as Record<string, Record<string, number>>).lastAutoTable)?.finalY ?? currentY + 40;
      currentY += 4;

      // Evidence subsection
      if (v.source_url || v.source_name || v.source_excerpt) {
        if (currentY > 230) {
          doc.addPage();
          currentY = 22;
        }

        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('EVIDENCE:', 18, currentY);
        currentY += 5;

        doc.setFont('helvetica', 'normal');

        const evidenceLines: string[][] = [];

        if (v.source_name) {
          evidenceLines.push(['Source', v.source_name]);
        }
        if (v.source_url) {
          evidenceLines.push(['URL', v.source_url]);
        }
        evidenceLines.push(['Retrieved', formatDate(v.found_at)]);
        if (v.source_excerpt) {
          const excerpt = v.source_excerpt.length > 100
            ? v.source_excerpt.substring(0, 100) + '...'
            : v.source_excerpt;
          evidenceLines.push(['Excerpt', `"${excerpt}"`]);
        }

        autoTable(doc, {
          startY: currentY,
          theme: 'plain',
          styles: { fontSize: 8, cellPadding: 2 },
          columnStyles: {
            0: { cellWidth: 30, fontStyle: 'bold', textColor: [80, 80, 80] },
            1: { cellWidth: 'auto' },
          },
          body: evidenceLines,
          margin: { left: 18, bottom: 35 },
        });

        currentY = ((doc as unknown as Record<string, Record<string, number>>).lastAutoTable)?.finalY ?? currentY + 20;
        currentY += 8;
      } else {
        currentY += 6;
      }
    });
  } else {
    doc.addPage();
    doc.setFontSize(14);
    doc.text('2. Violations & Evidence Record', 14, 22);
    doc.setFontSize(10);
    doc.text('No violations found on record for this supplier.', 14, 32);
  }

  // ── Risk Assessment (Simulation) ──

  if (simulation) {
    doc.addPage();
    doc.setFontSize(14);
    doc.text('3. Risk Assessment', 14, 22);

    autoTable(doc, {
      startY: 28,
      theme: 'grid',
      headStyles: { fillColor: [34, 87, 60] },
      head: [['Metric', 'Value']],
      body: [
        ['Risk Score', `${simulation.risk_score}/100`],
        ['Risk Level', simulation.risk_level.toUpperCase()],
        ['CSRD Compliant', simulation.csrd_compliant ? 'Yes' : 'No'],
        ['Financial Exposure', `EUR ${simulation.financial_exposure_eur.toLocaleString()}`],
        ['Recommended Action', simulation.recommended_action],
        ['Assessment Date', formatDate(simulation.simulated_at)],
      ],
      margin: { bottom: 35 },
    });

    // Pattern analysis section
    if (simulation.predictions && simulation.predictions.length > 0) {
      const predY = ((doc as unknown as Record<string, Record<string, number>>).lastAutoTable)?.finalY ?? 80;

      doc.setFontSize(12);
      doc.text('Pattern Analysis by Agent Type', 14, predY + 10);

      autoTable(doc, {
        startY: predY + 14,
        theme: 'grid',
        headStyles: { fillColor: [34, 87, 60] },
        head: [['Agent Type', 'Assessment', 'Confidence', 'Timeline']],
        body: simulation.predictions.map((p) => [
          p.agent_type.charAt(0).toUpperCase() + p.agent_type.slice(1),
          p.prediction,
          `${Math.round(p.probability * 100)}%`,
          `${p.timeline_days} days`,
        ]),
        margin: { bottom: 35 },
      });
    }
  }

  // ── Add footer to all pages ──
  addFooter(doc);

  return doc;
}
